version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["nginx"]
visible = "redirect_type == 'reverseproxy'"

[main.limit_size]
name.en = "Upload size limit"
name.fr = "Taille limite pour le téléchargement"
visible = "redirect_type == 'reverseproxy'"

[main.limit_size.upload_max_size]
ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
ask.en = "File upload size limit (Mb)"
type = "number"
bind = "null"

[main.proxy]
name.fr = "Redirection"
name.en = "Redirect"
visible = "redirect_type == 'reverseproxy'"

[main.proxy.proxy_pass]
ask.fr = "adresse proxy_pass"
ask.en = "proxy_pass to"
type = "url"
bind = "null"
optional = false
visible = "redirect_type == 'reverseproxy'"

[main.integration]
name.en = "Embedding"
name.fr = "Intégration"
[main.integration.allowed_urls]
ask.en = "Allow embedding from (URLs separated by spaces)"
ask.fr = "Liste des adresses web autorisées à intégrer cette application séparées par un espace"
type = "string"
bind = "null"
visible = "redirect_type == 'reverseproxy'"

