version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["nginx"]


[main.limit_size]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.limit_size.upload_max_size]
ask.fr = "Taille limite Nginx pour le téléchargement des fichiers en Mo"
ask.en = "Nginx limit size file upload (Mb)"
type = "number"
bind = "null"

[main.integration]
name.en = "Embedding"
name.fr = "Intégration"
[main.integration.allowed_urls]
ask.en = "Allow embedding from (URLs separated by spaces)"
ask.fr = "Liste des adresses web autorisées à intégrer cette application séparées par un espace"
type = "string"
bind = "null"
