#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

_validate_redirect_uri

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

echo "PWD=$(pwd)"
echo "PWD=$PWD"
echo "redirect_type=$redirect_type"
ls -la ../conf/
mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_add_nginx
echo "PWD=$(pwd)"
echo "PWD=$PWD"

ls -la ../conf/

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
