#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

upload_max_size="1"
allowed_urls=""

ynh_app_setting_set --key=upload_max_size --value=$upload_max_size
ynh_app_setting_set --key=allowed_urls --value=$allowed_urls

_validate_redirect_uri
_display_config_panel

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
