#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


ynh_app_setting_set_default --key=upload_max_size --value="1"
ynh_app_setting_set_default --key=allowed_urls --value=""
ynh_app_setting_set_default --key=redirect_path --value="$request_uri"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
else
    redirect_type="redirect"
fi
ynh_app_setting_set --key='redirect_type' --value=$redirect_type

if [[ -z "${target:-}" ]] && [[ -n "${redirect_path:-}" ]]; then
    target="$redirect_path"
    ynh_app_setting_delete --key=redirect_path
    ynh_app_setting_set --key=target --value="$target"
fi

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

mv ../conf/{nginx-$redirect_type.conf,nginx.conf}
ynh_config_add_nginx

ynh_script_progression "Upgrade of $app completed"
