#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
else
    redirect_type="redirect"
fi
ynh_app_setting_set --key='redirect_type' --value=$redirect_type

if [[ -z "${target:-}" ]] && [[ -n "${redirect_path:-}" ]]; then
    target="$redirect_path"
    ynh_app_setting_delete --key=redirect_path
    ynh_app_setting_set --key=target --value="$target"
fi

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

echo "PWD=$(pwd)"
echo "PWD=$PWD"
echo "redirect_type=$redirect_type"
ls -la ../conf/
ls -la /etc/yunohost/apps/$app/conf/

mv ../conf/{nginx-$redirect_type.conf,nginx.conf}
ls -la /etc/yunohost/apps/$app/conf/


ynh_config_add_nginx
ls -la /etc/yunohost/apps/$app/conf/

echo "PWD=$(pwd)"
echo "PWD=$PWD"

ls -la ../conf/

ynh_script_progression "Upgrade of $app completed"
